title: 유진정 기술블로그
email: yujin010917@khu.ac.kr
description: >- 
  Description도 생성해주면 좋겠네요.
baseurl: ""
url: "https://YuujInJeong.github.io"
github_username: YuujInJeong

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 10

# Analytics
google_analytics: UA-XXXXXXXX-X

# Timezone
timezone: Asia/Seoul

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include
include:
  - _pages

# Navigation
header_pages:
  - about.markdown
  - _posts
  - projects.md

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 1..6
  entity_output: as_char
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  footnote_nr: 1
  show_warnings: false